### ISSUE TITLE
where can I find the file deacot_file aka "/tmp/deacot2021.txt"

### ISSUE THREAD

**Issue by mendez97cr** [brad-darksbian/commodities-dashboard#1]
Mind helping me out. Fantastic read by the way! Thanks for getting my back into coding you hero.
 
Debug:
Deacot file does not exist.

**Comment by brad-darksbian** [comment]
Happy to help - 

You didn't provide an output of what you're seeing in the terminal, so I'm kind of flying a bit blind.  However, I think I know the issue.  But, first things first.

Make sure you have python set up properly and your environment has the necessary modules installed per the requirements.txt.  If all of that is taken care of, with the files brought down from the repository, executing:

python /path/to/main.py

or

python3 /path/to/main.py

on a linux / osx system will automatically go to the location and pull the most recent file and place it in /tmp

If you changed paths to place the file elsewhere, grab the most recent version from the repo.  I just uploaded a fix for a path issue between downloading and reading processes for the report files.

If all of that does not work, let me know and I'll work with you on it to get you up and running.  If this does work, just let me know and I'll close the issue.

Thanks!

Brad

**Comment by brad-darksbian** [comment]
Closing the issue. Can be reopened with new data.
